fix middleware miss route problem
laurentS/slowapi pull request #30
Opened 2021-01-08 08:16 UTC by xuxygo

hi, During my use, I found that route was overwritten as the last one, and exempt could not take effect.So I submitted a version to fix

2021-01-10 15:25 UTC, laurentS commented
Hi @xuxygo! thank you for submitting this PR. Could you share some example use case that shows the error you were having? I don't understand what the problem was. Thanks!

2021-01-11 06:29 UTC, xuxygo commented
> Hi @xuxygo! thank you for submitting this PR. Could you share some example use case that shows the error you were having? I don't understand what the problem was. Thanks!

Hi, when i add multiple exempt, the module name in the middleware will get the name of the last route
```
    def test_execmpt_route(self):
        app, limiter = self.build_fastapi_app(key_func=get_ipaddr, headers_enabled=True)

        @app.get("/t4")
        @app.state.limiter.exempt
        def t4(request: Request, response: str = None):
            return {"key": "value"}

        @app.get("/t5")
        @limiter.exempt
        def t5(request: Request, response: str = None):
            return {"key": "value"}

        @app.get("/t6")
        @limiter.limit("5/minute")
        def t6(request: Request, response: str = None):
            return {"key": "value"}

        with pytest.raises(Exception) as exc_info:
            client = TestClient(app)
            client.get("/t5")
            client.get("/t6")
        assert exc_info.match(
            r"""parameter `response` must be an instance of starlette.responses.Response"""
        )
```
when running the above code,  the name will like this
```
route_name is tests.test_fastapi_extension.t6
url route is /t5
route_name is tests.test_fastapi_extension.t6
url route is /t6
```

2021-01-11 22:01 UTC, laurentS requested changes
It took me a moment to understand what is happening here, but you're right, the code in the middleware is incorrect. Your test code works for me with or without your fix however, so I don't think it exhibits the issue. Do you have a test that actually fails without your change?

2021-01-12 01:29 UTC, xuxygo commented on slowapi/middleware.py
> +            if match.FULL == match and hasattr(route, "endpoint"):
yeah, you're right and I will revise and submit.

2021-01-12 01:41 UTC, xuxygo commented
> It took me a moment to understand what is happening here, but you're right, the code in the middleware is incorrect. Your test code works for me with or without your fix however, so I don't think it exhibits the issue. Do you have a test that actually fails without your change?

Yes, if i do not make changes, some routes will not be properly restricted

2021-02-21 22:28 UTC, laurentS approved these changes

2021-02-21 22:28 UTC, merged